---
title: "Team 5"
subtitle: "STA 199 Project"
format: html
editor: visual
---

Utilizing the airlines data set from the CORGIS Data Project, we explored the question: Of the top five busiest airports in the U.S., when and where are there the most flight delays and/or cancellations? To do so, we began with performing data manipulation to decrease the number of airports we were examining (airports selected were the top five busiest airports in the U.S.) and to create an **airlines_season** variable to classify the flights by time of year. We then created visualizations and calculated the mean number of delays and cancellations for each chosen airport to make a preliminary determination about how the season impacted the number of flight delays and cancellations. Further analysis included the creation of both simple and multiple linear regression models. Simple models demonstrated the relationship between the season and the number of flight delays or cancellations. On the other hand, the interactive multiple models demonstrated the relationship between the season, the airport, and the number of flight delays or cancellations. While we were able to conclude that the highest number of delays occurred during the summer and the highest number of cancellations occurred during the winter, we suggest that future researchers explore the relationships between delays/cancellations and other variables such as the airport.
