---
title: "The Statistics of Airlines"
subtitle: "Cancellations and Delays"
format: html
editor: visual
execute:
  echo: true
---

## Introduction and data

[CORGIS Datasets Project (vt.edu)](https://think.cs.vt.edu/corgis/csv/airlines/)

This data is from the CORGIS Data Set Project. This is the second version of this data set, and it was created by Austin Cory Bart. The data set was created on March 27, 2015. There is little information on how the data was collected; however, it is likely that the statistician took a retrospective approach, looking at past monthly records for different airports across the United States starting in 2003. Each observation is based on an airport code (shorthand for the airport's full name) and a specific time (year/month). For each observation, there are different variables to identify how many flights were delayed (and for what reason), cancelled, diverted, or on time.

Based on this data set our research question is: **Why do flight delays and cancellations occur at different times of the year?** We want to answer this research question because flight delays and cancellations often give passengers grief and stress at all different times of the year. However, our question explores whether there is a specific time of year when flights are particularly prone to delays and cancellations and for what reason. In turn, this would help those looking to fly to know how to best plan for trips that might be impacted by flight changes. Working to understand why such issues occur would also be crucial, both in determining whether certain cancellations or delays can be avoided and in providing some perspective to passengers who have struggled with flight plans in the past.

Based on the past literature on the times of year flights are subject to the most cancellations and delays, we hypothesize that the time most prone to flight cancellations and delays is during the summer months (June through August) due to late aircrafts as so many people choose to fly during this time.

Published on July 1st, 2022, the NYT article "Understanding the Summer Air Travel Mess" discusses the challenges faced by travelers during the summer months due to mass delays and cancellations. As a result of being the busiest time of the year, factors such as weather, staffing shortages, and equipment issues have a much more significant impact on schedule disruption. Just last year, low-cost carriers like JetBlue and Spirit canceled 10.3 and 9 percent of flights in April. The article also provides advice on how to minimize the impact of flight delays: book direct flights and choose early morning departures. It's also smart to avoid flying during weekends. Most importantly, though, "never book the last flight of the day." Additionally, Murphy writes about the implications these cancellations have on airlines, damaging them both financially and reputation wise. New technologies may be implemented, but, at "the heart of the issue," airlines respond to supply and demand, increasing flights when people travel more.

Murphy, Heather. "Understanding the Summer Air Travel Mess." The New York Times, The New York Times, 1 July 2022, https://www.nytimes.com/2022/07/01/travel/summer-travel-flight-delays-cancellations.html.

We are utilizing mostly quantitative variables in this research, which the exception of the month data, airline information, and airport information (categorical). Quantitative variables used will include the number of flights delayed and cancelled for a variety of reasons at different airports across the country.
